version: 0.2
phases:
  build:
    commands:
      - echo mvn -v
      - mvn clean test -DsuiteXmlFile="src/test/resources/runner/sanity.xml"
      - echo Build started on `date`
      - | # saving result for conditional rollback
        if grep -q "Failure:" target/surefire-reports/index.html; then
            echo "tests has failures!" && echo "Fail" > result.txt && exit 1;
        else
            echo "tests all passed" && echo "Pass" > result.txt;
        fi
reports:
  rest-api-automation:
    files:
      - "reports/**/*"
    discard-paths: no
    file-format: TestNGXml
artifacts:
    files:
      - target/surefire-reports/index.html