version: 0.2
phases:
  build:
    commands:
      - mvn -v
      - mvn clean test -DsuiteXmlFile="src/test/resources/runner/sanity.xml"
      - echo Build started on `date`
      - | # saving result for conditional rollback
        if grep -q "Failure:" target/surefire-reports/index.html; then
            echo "tests has failures!" && echo "Fail" > result.txt && exit 1;
        else
            echo "tests all passed" && echo "Pass" > result.txt;
        fi
  post_build:
    commands:
      - aws s3 --recursive rm s3://testreportbuckect/emailable-report.html
      - aws s3 cp ./target/surefire-reports/emailable-report.html  s3://testreportbuckect/emailable-report.html
      - aws s3 --recursive rm s3://testreportbuckect/index.html
      - aws s3 cp ./target/surefire-reports/index.html  s3://testreportbuckect/index.html

reports:
  rest-api-automation:
    files:
      - "target/surefire-reports/**/*"
    discard-paths: no
    file-format: TestNGXml
